In [10]:
import pandas as pd

file_name = "Day7_Student_dataset.csv"
student_data = pd.read_csv("Day7_Student_Dataset.csv")
print("Dataset loaded successfully.")

print("========== COMPLETE DATASET ==========")
display(student_data)

print("========== FIRST 10 ROWS ==========")
display(student_data.head(10))

print("========== LAST 10 ROWS ==========")
display(student_data.tail(10))

print("========== RANDOM SAMPLE ==========")
display(student_data.sample(5))

print("========== DATASET SHAPE ==========")
number_of_rows = student_data.shape[0]
number_of_columns = student_data.shape[1]
print(f"Number of rows: {number_of_rows}")
print(f"Number of columns: {number_of_columns}")
print(f"Dataset shape: {student_data.shape}")

print("========== COLUMN NAMES ==========")
column_names = student_data.columns.tolist()
for column_name in column_names:
  print(column_name)

print("========== DATASET INDEX ==========")
print(student_data.index)
print("\nIndex values:")
print(student_data.index.tolist())

print("========== DATA TYPES ==========")
print(student_data.dtypes)

print("========== DATASET INFORMATION ==========")
student_data.info()

print("========== DESCRIPTIVE STATISTICS ==========")
display(student_data.describe())

print("========== ALL COLUMN STATISTICS ==========")
display(student_data.describe(include="all"))

print("========== MISSING VALUES BY COLUMN ==========")
missing_values = student_data.isnull().sum()
print(missing_values)

print("========== TOTAL MISSING VALUES ==========")
total_missing_values = student_data.isnull().sum().sum()
print(f"Total missing values: {total_missing_values}")

print("========== ROWS WITH MISSING VALUES ==========")
missing_rows = student_data[
    student_data.isnull().any(axis=1)
]
display(missing_rows)

print("========== UNIQUE VALUES ==========")
unique_values = student_data.nunique()
print(unique_values)

print("========== STUDENT BY COURSE ==========")
course_counts = student_data["Course"].value_counts()
print(course_counts)

print("========== STUDENTS BY CITY ==========")
city_counts = student_data["City"].value_counts()
print(city_counts)

print("========== AGE ANALYSIS ==========")
average_age = student_data["Age"].mean()
median_age = student_data["Age"].median()
minimum_age = student_data["Age"].min()
maximum_age = student_data["Age"].max()
print(f"Average age: {average_age:.2f}")
print(f"Median age: {median_age:.2f}")
print(f"Minimum age: {minimum_age}")
print(f"Maximum age: {maximum_age}")

print("========== MARKS ANALYSIS ==========")
average_marks = student_data["Marks"].mean()
median_marks = student_data["Marks"].median()
minimum_marks = student_data["Marks"].min()
maximum_marks = student_data["Marks"].max()
print(f"Average marks: {average_marks:.2f}")
print(f"Median marks: {median_marks:.2f}")
print(f"Minimum marks: {minimum_marks:.2f}")
print(f"Maximum marks: {maximum_marks:.2f}")

print("========== ATTENDANCE ANALYSIS ==========")
average_attendance = (
    student_data["Attendance_Percentage"].mean()
)
median_attendance = (
    student_data["Attendance_Percentage"].median()
)
minimum_attendance = (
    student_data["Attendance_Percentage"].min()
)
maximum_attendance = (
    student_data["Attendance_Percentage"].max()
)
print(f"Average attendance: {average_attendance:.2f}%")
print(f"Median attendance: {median_attendance:.2f}%")
print(f"Minimum attendance: {minimum_attendance:.2f}%")
print(f"Maximum attendance: {maximum_attendance:.2f}%")

print("========== HIGHEST-SCORING STUDENT ==========")
highest_marks_index = student_data["Marks"].idxmax()
highest_marks_student = student_data.loc[highest_marks_index]
display(highest_marks_student)

print("========== LOWEST-SCORING STUDENT ==========")
lowest_marks_index = student_data["Marks"].idxmin()
lowest_marks_student = student_data.loc[lowest_marks_index]
display(lowest_marks_student)

print("========== MOST POPULAR COURSE ==========")
most_popular_course = (
    student_data["Course"].value_counts().idxmax()
)
course_student_count = (
    student_data["Course"].value_counts().max()
)
print(f"Most popular course: {most_popular_course}")
print(f"Number of students: {course_student_count}")

print("========== MOST REPRESENTED CITY ==========")
most_common_city = (
    student_data["City"].value_counts().idxmax()
)
city_student_count = (
    student_data["City"].value_counts().max()
)
print(f"Most represented city: {most_common_city}")
print(f"Number of students: {city_student_count}")

print("=" * 60)
print("                     FINAL DATASET SUMMARY")
print("=" * 60)
print(f"Total students: {number_of_rows}")
print(f"Total columns: {number_of_columns}")
print(f"Average age: {average_age:.2f}")
print(f"Average marks: {average_marks:.2f}")
print(f"Median marks: {median_marks:.2f}")
print(f"Highest marks: {maximum_marks:.2f}")
print(f"Lowest marks: {minimum_marks:.2f}")
print(f"Average attendance: {average_attendance:.2f}%")
print(f"Total missing values: {total_missing_values}")
print(f"Most popular course: {most_popular_course}")
print(f"Most represented city: {most_common_city}")
print("=" * 60)

Dataset loaded successfully.
========== COMPLETE DATASET ==========

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

========== FIRST 10 ROWS ==========

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

========== LAST 10 ROWS ==========

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

========== RANDOM SAMPLE ==========

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar

========== DATASET SHAPE ==========
Number of rows: 25
Number of columns: 7
Dataset shape: (25, 7)
========== COLUMN NAMES ==========
Student_ID
Name
Age
Course
Marks
Attendance_Percentage
City
========== DATASET INDEX ==========
RangeIndex(start=0, stop=25, step=1)

Index values:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
========== DATA TYPES ==========
Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object
========== DATASET INFORMATION ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB
========== DESCRIPTIVE STATISTICS ==========

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

========== ALL COLUMN STATISTICS ==========

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
count,25.000000,25,25.000000,25,24.000000,24.000000,24
unique,NaN,25,NaN,3,NaN,NaN,13
top,NaN,Aarav Sharma,NaN,Data Science,NaN,NaN,Srinagar
freq,NaN,1,NaN,9,NaN,NaN,6
mean,1013.000000,NaN,20.000000,NaN,82.250000,87.083333,NaN
std,7.359801,NaN,1.414214,NaN,8.689074,7.252686,NaN
min,1001.000000,NaN,18.000000,NaN,68.000000,72.000000,NaN
25%,1007.000000,NaN,19.000000,NaN,75.500000,82.750000,NaN
50%,1013.000000,NaN,20.000000,NaN,82.500000,88.000000,NaN
75%,1019.000000,NaN,21.000000,NaN,89.250000,92.250000,NaN
max,1025.000000,NaN,23.000000,NaN,96.000000,98.000000,NaN

========== MISSING VALUES BY COLUMN ==========
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64
========== TOTAL MISSING VALUES ==========
Total missing values: 3
========== ROWS WITH MISSING VALUES ==========

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar

========== UNIQUE VALUES ==========
Student_ID               25
Name                     25
Age                       6
Course                    3
Marks                    24
Attendance_Percentage    22
City                     13
dtype: int64
========== STUDENT BY COURSE ==========
Course
Data Science        9
AI                  8
Computer Science    8
Name: count, dtype: int64
========== STUDENTS BY CITY ==========
City
Srinagar      6
Delhi         3
Bengaluru     2
Hyderabad     2
Pune          2
Kolkata       2
Mumbai        1
Lucknow       1
Kochi         1
Jaipur        1
Chandigarh    1
Ahmedabad     1
Chennai       1
Name: count, dtype: int64
========== AGE ANALYSIS ==========
Average age: 20.00
Median age: 20.00
Minimum age: 18
Maximum age: 23
========== MARKS ANALYSIS ==========
Average marks: 82.25
Median marks: 82.50
Minimum marks: 68.00
Maximum marks: 96.00
========== ATTENDANCE ANALYSIS ==========
Average attendance: 87.08%
Median attendance: 88.00%
Minimum attendance: 72.00%
Maximum attendance: 98.00%
========== HIGHEST-SCORING STUDENT ==========

Student_ID                       1022
Name                       Alina Shah
Age                                19
Course                   Data Science
Marks                            96.0
Attendance_Percentage            98.0
City                         Srinagar
Name: 21, dtype: object

========== LOWEST-SCORING STUDENT ==========

Student_ID                           1012
Name                            Aisha Mir
Age                                    19
Course                   Computer Science
Marks                                68.0
Attendance_Percentage                72.0
City                                Delhi
Name: 11, dtype: object

========== MOST POPULAR COURSE ==========
Most popular course: Data Science
Number of students: 9
========== MOST REPRESENTED CITY ==========
Most represented city: Srinagar
Number of students: 6
============================================================
                     FINAL DATASET SUMMARY
============================================================
Total students: 25
Total columns: 7
Average age: 20.00
Average marks: 82.25
Median marks: 82.50
Highest marks: 96.00
Lowest marks: 68.00
Average attendance: 87.08%
Total missing values: 3
Most popular course: Data Science
Most represented city: Srinagar
============================================================